class Product {
    constructor(name, desc, fullDesc, price, image) {
        this.name = name
        this.desc = desc
        this.fullDesc = fullDesc
        this.price = price
        this.image = image
    }
}

const products = [
    new Product("Keyboard", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 30, "/images/keyboard.webp"),
    new Product("Scotch Tape", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 10, "/images/scotch_tape.webp"),
    new Product("Sandal", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 10, "/images/sandal.webp"),
    new Product("Sun Glasses", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 5, "/images/sun_glasses.webp"),
    new Product("Television", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 70, "/images/television.webp"),
    new Product("Washing Machine", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 60, "/images/washing_machine.webp"),
    new Product("Paper Bag", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 10, "/images/bag.webp"),
    new Product("Boom Box", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 30, "/images/boom_box.webp"),
    new Product("Computer", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 100, "/images/computer.webp"),
    new Product("Radio", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 20, "/images/radio.webp"),
    new Product("Mirror", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur.", "Adipisicing nostrud in exercitation eu tempor adipisicing. Dolor fugiat quis eiusmod eu incididunt excepteur ex id consectetur adipisicing officia excepteur. Cupidatat in consequat est nostrud non do reprehenderit adipisicing sunt deserunt irure do magna mollit.", 10, "/images/mirror.webp"),
];

export default products;